#!/usr/bin/env python3
"""
RAG Research Agent — CDK App Entry Point
Generated by CDK CICD Template Library
"""
import os
import aws_cdk as cdk
from infrastructure.app_stage import AppStage
from infrastructure.pipeline_stack import PipelineStack

app = cdk.App()

# Environment configuration
account = os.environ.get("CDK_DEFAULT_ACCOUNT", app.node.try_get_context("account"))
region = os.environ.get("CDK_DEFAULT_REGION", app.node.try_get_context("region") or "us-east-1")

env = cdk.Environment(account=account, region=region)

# Pipeline stack (self-mutating CICD)
PipelineStack(
    app, "RagResearchAgentPipeline",
    env=env,
    description="RAG Research Agent — Self-mutating CICD Pipeline",
)

# Standalone stack for local development / cdk deploy
AppStage(
    app, "RagResearchAgentDev",
    env=env,
    stage_name="dev",
)

app.synth()
