"""
RAG Research Agent — Full System App Stack
Generated by CDK CICD Template Library (Pass 2A)

Layers:
  0. Networking (VPC, subnets, security groups, VPC endpoints)
  1. Security (KMS, IAM, CloudTrail)
  2. Data (DynamoDB, S3, OpenSearch Serverless)
  3. Backend (Lambda microservices, ECS Fargate)
  4. API (API Gateway REST + Cognito)
  5. Frontend (S3 + CloudFront + WAF)
  6. Observability (CloudWatch, X-Ray, SNS)
  7. LLMOps (Bedrock Knowledge Base, Guardrails)
  8. Strands Agent Runtime (agent Lambda, sessions, artifacts)
  9. Strands AgentCore (Gateway MCP, Memory, OAuth2)
  10. Strands Agent Frontend (WebSocket API, React config)
  11. Strands Agent Eval (golden datasets, eval pipeline, CICD gate)
"""
import json
from typing import Dict

import aws_cdk as cdk
from aws_cdk import (
    Duration,
    RemovalPolicy,
    CfnOutput,
    Stack,
    aws_ec2 as ec2,
    aws_iam as iam,
    aws_kms as kms,
    aws_s3 as s3,
    aws_dynamodb as ddb,
    aws_lambda as _lambda,
    aws_logs as logs,
    aws_ecs as ecs,
    aws_secretsmanager as sm,
    aws_apigateway as apigw,
    aws_apigatewayv2 as apigwv2,
    aws_cognito as cognito,
    aws_cloudfront as cloudfront,
    aws_cloudfront_origins as origins,
    aws_wafv2 as wafv2,
    aws_cloudwatch as cw,
    aws_cloudwatch_actions as cw_actions,
    aws_sns as sns,
    aws_sns_subscriptions as sns_subs,
    aws_ssm as ssm,
    aws_stepfunctions as sfn,
    aws_stepfunctions_tasks as sfn_tasks,
    aws_cloudtrail as cloudtrail,
)
from constructs import Construct


class AppStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, stage_name: str = "dev", **kwargs):
        super().__init__(scope, construct_id, **kwargs)

        self.project_name = "rag-research-agent"
        self.stage_name = stage_name

        # Execute layers in dependency order
        self._create_networking(stage_name)
        self._create_security(stage_name)
        self._create_data_layer(stage_name)
        self._create_observability(stage_name)
        self._create_llmops(stage_name)
        self._create_strands_agent_runtime(stage_name)
        self._create_api_layer(stage_name)
        self._create_strands_agent_frontend(stage_name)
        self._create_strands_agentcore(stage_name)
        self._create_strands_agent_eval(stage_name)
        self._create_frontend(stage_name)

    # =========================================================================
    # LAYER 0: NETWORKING
    # =========================================================================
    def _create_networking(self, stage_name: str) -> None:
        az_count = 2 if stage_name == "dev" else 3

        self.vpc = ec2.Vpc(
            self, "VPC",
            vpc_name=f"{self.project_name}-vpc-{stage_name}",
            ip_addresses=ec2.IpAddresses.cidr(
                "10.10.0.0/16" if stage_name == "prod" else "10.20.0.0/16"
            ),
            max_azs=az_count,
            subnet_configuration=[
                ec2.SubnetConfiguration(name="Public", subnet_type=ec2.SubnetType.PUBLIC, cidr_mask=24),
                ec2.SubnetConfiguration(name="Private", subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS, cidr_mask=24),
                ec2.SubnetConfiguration(name="Isolated", subnet_type=ec2.SubnetType.PRIVATE_ISOLATED, cidr_mask=24),
            ],
            nat_gateways=az_count if stage_name == "prod" else 1,
            enable_dns_hostnames=True,
            enable_dns_support=True,
            flow_logs={
                "VPCFlowLogs": ec2.FlowLogOptions(
                    destination=ec2.FlowLogDestination.to_cloud_watch_logs(
                        log_group=logs.LogGroup(
                            self, "VPCFlowLogs",
                            log_group_name=f"/{self.project_name}/{stage_name}/vpc-flow-logs",
                            retention=logs.RetentionDays.ONE_MONTH if stage_name != "prod" else logs.RetentionDays.ONE_YEAR,
                            removal_policy=RemovalPolicy.DESTROY,
                        ),
                    ),
                    traffic_type=ec2.FlowLogTrafficType.ALL,
                )
            },
        )

        # VPC Gateway Endpoints (free)
        self.vpc.add_gateway_endpoint("S3Endpoint", service=ec2.GatewayVpcEndpointAwsService.S3)
        self.vpc.add_gateway_endpoint("DynamoDBEndpoint", service=ec2.GatewayVpcEndpointAwsService.DYNAMODB)

        # Interface endpoints
        endpoint_sg = ec2.SecurityGroup(self, "VPCEndpointSG", vpc=self.vpc, allow_all_outbound=False)
        endpoint_sg.add_ingress_rule(ec2.Peer.ipv4(self.vpc.vpc_cidr_block), ec2.Port.tcp(443))

        for eid, svc in [
            ("SecretsManager", ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER),
            ("SSM", ec2.InterfaceVpcEndpointAwsService.SSM),
            ("STS", ec2.InterfaceVpcEndpointAwsService.STS),
            ("CWLogs", ec2.InterfaceVpcEndpointAwsService.CLOUDWATCH_LOGS),
        ]:
            self.vpc.add_interface_endpoint(eid, service=svc, security_groups=[endpoint_sg],
                subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS), private_dns_enabled=True)

        # Security Groups
        self.lambda_sg = ec2.SecurityGroup(self, "LambdaSG", vpc=self.vpc, allow_all_outbound=False,
            security_group_name=f"{self.project_name}-lambda-sg-{stage_name}")
        self.lambda_sg.add_egress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(443), "HTTPS egress")

        self.ecs_sg = ec2.SecurityGroup(self, "EcsSG", vpc=self.vpc, allow_all_outbound=False,
            security_group_name=f"{self.project_name}-ecs-sg-{stage_name}")
        self.ecs_sg.add_egress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(443), "HTTPS egress")

    # =========================================================================
    # LAYER 1: SECURITY
    # =========================================================================
    def _create_security(self, stage_name: str) -> None:
        self.kms_key = kms.Key(
            self, "MasterKey",
            alias=f"alias/{self.project_name}-master-{stage_name}",
            description=f"Master encryption key ({stage_name})",
            enable_key_rotation=True,
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
        )

        self.pipeline_key = kms.Key(
            self, "PipelineKey",
            alias=f"alias/{self.project_name}-pipeline-{stage_name}",
            enable_key_rotation=True,
            removal_policy=RemovalPolicy.DESTROY,
        )

        # CloudTrail
        trail_bucket = s3.Bucket(
            self, "CloudTrailBucket",
            bucket_name=f"{self.project_name}-cloudtrail-{stage_name}-{self.account}",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.KMS,
            encryption_key=self.kms_key,
            versioned=True,
            lifecycle_rules=[s3.LifecycleRule(expiration=Duration.days(365 * 7))],
            removal_policy=RemovalPolicy.RETAIN,
        )

        trail = cloudtrail.Trail(
            self, "AuditTrail",
            trail_name=f"{self.project_name}-audit-{stage_name}",
            bucket=trail_bucket,
            send_to_cloud_watch_logs=True,
            cloud_watch_logs_retention=logs.RetentionDays.ONE_YEAR,
            encryption_key=self.kms_key,
            enable_file_validation=True,
            is_multi_region_trail=stage_name == "prod",
            include_global_service_events=True,
        )
        trail.log_all_s3_data_events()
        trail.log_all_lambda_data_events()

    # =========================================================================
    # LAYER 2: DATA
    # =========================================================================
    def _create_data_layer(self, stage_name: str) -> None:
        import aws_cdk.aws_opensearchserverless as aoss

        # --- S3 Buckets ---
        self.documents_bucket = s3.Bucket(
            self, "DocumentsBucket",
            bucket_name=f"{self.project_name}-documents-{stage_name}-{self.account}",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.KMS,
            encryption_key=self.kms_key,
            versioned=True,
            enforce_ssl=True,
            lifecycle_rules=[
                s3.LifecycleRule(transitions=[
                    s3.Transition(storage_class=s3.StorageClass.INTELLIGENT_TIERING, transition_after=Duration.days(30)),
                ]),
            ],
            event_bridge_enabled=True,
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
            auto_delete_objects=stage_name != "prod",
        )

        self.agent_artifacts_bucket = s3.Bucket(
            self, "AgentArtifactsBucket",
            bucket_name=f"{self.project_name}-agent-artifacts-{stage_name}-{self.account}",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.KMS,
            encryption_key=self.kms_key,
            versioned=True,
            enforce_ssl=True,
            lifecycle_rules=[s3.LifecycleRule(expiration=Duration.days(90))],
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
            auto_delete_objects=stage_name != "prod",
        )

        # --- DynamoDB: Agent Sessions ---
        self.agent_session_table = ddb.Table(
            self, "AgentSessionTable",
            table_name=f"{self.project_name}-agent-sessions-{stage_name}",
            partition_key=ddb.Attribute(name="session_id", type=ddb.AttributeType.STRING),
            sort_key=ddb.Attribute(name="turn_id", type=ddb.AttributeType.NUMBER),
            billing_mode=ddb.BillingMode.PAY_PER_REQUEST,
            point_in_time_recovery=True,
            encryption=ddb.TableEncryption.CUSTOMER_MANAGED,
            encryption_key=self.kms_key,
            time_to_live_attribute="ttl",
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
        )
        self.agent_session_table.add_global_secondary_index(
            index_name="actor-sessions-idx",
            partition_key=ddb.Attribute(name="actor_id", type=ddb.AttributeType.STRING),
            sort_key=ddb.Attribute(name="created_at", type=ddb.AttributeType.STRING),
            projection_type=ddb.ProjectionType.ALL,
        )

        # --- DynamoDB: Eval Results ---
        self.eval_results_table = ddb.Table(
            self, "AgentEvalResultsTable",
            table_name=f"{self.project_name}-agent-eval-results-{stage_name}",
            partition_key=ddb.Attribute(name="eval_run_id", type=ddb.AttributeType.STRING),
            sort_key=ddb.Attribute(name="test_case_id", type=ddb.AttributeType.STRING),
            billing_mode=ddb.BillingMode.PAY_PER_REQUEST,
            point_in_time_recovery=True,
            time_to_live_attribute="ttl",
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
        )
        self.eval_results_table.add_global_secondary_index(
            index_name="dataset-version-idx",
            partition_key=ddb.Attribute(name="dataset_version", type=ddb.AttributeType.STRING),
            sort_key=ddb.Attribute(name="created_at", type=ddb.AttributeType.STRING),
            projection_type=ddb.ProjectionType.ALL,
        )

        # --- OpenSearch Serverless (Vector Store) ---
        collection_name = f"{self.project_name[:20]}-vec-{stage_name[:3]}"

        aoss.CfnSecurityPolicy(
            self, "VectorStoreEncPolicy",
            name=f"{self.project_name[:22]}-enc-{stage_name[:3]}",
            type="encryption",
            policy=json.dumps({
                "Rules": [{"Resource": [f"collection/{collection_name}"], "ResourceType": "collection"}],
                "AWSOwnedKey": True,
            }),
        )

        aoss.CfnSecurityPolicy(
            self, "VectorStoreNetPolicy",
            name=f"{self.project_name[:22]}-net-{stage_name[:3]}",
            type="network",
            policy=json.dumps([{
                "Description": "Public access for KB sync",
                "Rules": [
                    {"Resource": [f"collection/{collection_name}"], "ResourceType": "collection"},
                    {"Resource": [f"collection/{collection_name}"], "ResourceType": "dashboard"},
                ],
                "AllowFromPublic": True,
            }]),
        )

        self.vector_store = aoss.CfnCollection(
            self, "VectorStore",
            name=collection_name,
            description=f"Vector store for RAG knowledge base ({stage_name})",
            type="VECTORSEARCH",
            standby_replicas="ENABLED" if stage_name == "prod" else "DISABLED",
        )

        # --- Eval Dataset Bucket ---
        self.eval_dataset_bucket = s3.Bucket(
            self, "AgentEvalDatasetBucket",
            bucket_name=f"{self.project_name}-eval-datasets-{stage_name}-{self.account}",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.KMS,
            encryption_key=self.kms_key,
            versioned=True,
            enforce_ssl=True,
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
            auto_delete_objects=stage_name != "prod",
        )

    # =========================================================================
    # LAYER 6: OBSERVABILITY
    # =========================================================================
    def _create_observability(self, stage_name: str) -> None:
        self.alert_topic = sns.Topic(
            self, "AlertTopic",
            topic_name=f"{self.project_name}-alerts-{stage_name}",
            master_key=self.kms_key,
        )

    # =========================================================================
    # LAYER 7: LLMOPS (Bedrock Knowledge Base + Guardrails)
    # =========================================================================
    def _create_llmops(self, stage_name: str) -> None:
        import aws_cdk.aws_bedrock as bedrock

        # Bedrock KB Role
        self.bedrock_kb_role = iam.Role(
            self, "BedrockKBRole",
            assumed_by=iam.ServicePrincipal("bedrock.amazonaws.com"),
            role_name=f"{self.project_name}-bedrock-kb-{stage_name}",
        )
        self.documents_bucket.grant_read(self.bedrock_kb_role)
        self.kms_key.grant_encrypt_decrypt(self.bedrock_kb_role)
        self.bedrock_kb_role.add_to_policy(iam.PolicyStatement(
            actions=["aoss:APIAccessAll"],
            resources=[self.vector_store.attr_arn],
        ))
        self.bedrock_kb_role.add_to_policy(iam.PolicyStatement(
            actions=["bedrock:InvokeModel"],
            resources=[f"arn:aws:bedrock:{self.region}::foundation-model/amazon.titan-embed-text-v2:0"],
        ))

        # AOSS Data Access Policy
        import aws_cdk.aws_opensearchserverless as aoss
        aoss.CfnAccessPolicy(
            self, "VectorStoreDataPolicy",
            name=f"{self.project_name[:22]}-dat-{stage_name[:3]}",
            type="data",
            policy=json.dumps([{
                "Description": "KB and agent access",
                "Rules": [
                    {"Resource": [f"collection/{self.vector_store.name}"], "Permission": [
                        "aoss:CreateCollectionItems", "aoss:DeleteCollectionItems",
                        "aoss:UpdateCollectionItems", "aoss:DescribeCollectionItems"],
                     "ResourceType": "collection"},
                    {"Resource": [f"index/{self.vector_store.name}/*"], "Permission": [
                        "aoss:CreateIndex", "aoss:DeleteIndex", "aoss:UpdateIndex",
                        "aoss:DescribeIndex", "aoss:ReadDocument", "aoss:WriteDocument"],
                     "ResourceType": "index"},
                ],
                "Principal": [self.bedrock_kb_role.role_arn],
            }]),
        )

        # Knowledge Base
        self.knowledge_base = bedrock.CfnKnowledgeBase(
            self, "ResearchKB",
            name=f"{self.project_name}-kb-{stage_name}",
            description="Research documents knowledge base for RAG",
            role_arn=self.bedrock_kb_role.role_arn,
            knowledge_base_configuration=bedrock.CfnKnowledgeBase.KnowledgeBaseConfigurationProperty(
                type="VECTOR",
                vector_knowledge_base_configuration=bedrock.CfnKnowledgeBase.VectorKnowledgeBaseConfigurationProperty(
                    embedding_model_arn=f"arn:aws:bedrock:{self.region}::foundation-model/amazon.titan-embed-text-v2:0",
                    embedding_model_configuration=bedrock.CfnKnowledgeBase.EmbeddingModelConfigurationProperty(
                        bedrock_embedding_model_configuration=bedrock.CfnKnowledgeBase.BedrockEmbeddingModelConfigurationProperty(
                            dimensions=1024,
                        )
                    ),
                ),
            ),
            storage_configuration=bedrock.CfnKnowledgeBase.StorageConfigurationProperty(
                type="OPENSEARCH_SERVERLESS",
                opensearch_serverless_configuration=bedrock.CfnKnowledgeBase.OpenSearchServerlessConfigurationProperty(
                    collection_arn=self.vector_store.attr_arn,
                    vector_index_name=f"{self.project_name}-{stage_name}-index",
                    field_mapping=bedrock.CfnKnowledgeBase.OpenSearchServerlessFieldMappingProperty(
                        vector_field="embedding", text_field="text", metadata_field="metadata",
                    ),
                ),
            ),
        )

        # Data Source
        bedrock.CfnDataSource(
            self, "KBDataSource",
            name=f"{self.project_name}-docs-{stage_name}",
            knowledge_base_id=self.knowledge_base.attr_knowledge_base_id,
            data_source_configuration=bedrock.CfnDataSource.DataSourceConfigurationProperty(
                type="S3",
                s3_configuration=bedrock.CfnDataSource.S3DataSourceConfigurationProperty(
                    bucket_arn=self.documents_bucket.bucket_arn,
                    inclusion_prefixes=["documents/"],
                ),
            ),
            vector_ingestion_configuration=bedrock.CfnDataSource.VectorIngestionConfigurationProperty(
                chunking_configuration=bedrock.CfnDataSource.ChunkingConfigurationProperty(
                    chunking_strategy="HIERARCHICAL",
                    hierarchical_chunking_configuration=bedrock.CfnDataSource.HierarchicalChunkingConfigurationProperty(
                        level_configurations=[
                            bedrock.CfnDataSource.HierarchicalChunkingLevelConfigurationProperty(max_token_count=1500),
                            bedrock.CfnDataSource.HierarchicalChunkingLevelConfigurationProperty(max_token_count=300),
                        ],
                        overlap_tokens=60,
                    ),
                ),
            ),
        )

        # Guardrails
        self.guardrail = bedrock.CfnGuardrail(
            self, "BedrockGuardrail",
            name=f"{self.project_name}-guardrail-{stage_name}",
            description="Safety guardrails for RAG Research Agent",
            content_policy_config=bedrock.CfnGuardrail.ContentPolicyConfigProperty(
                filters_config=[
                    bedrock.CfnGuardrail.ContentFilterConfigProperty(type="SEXUAL", input_strength="HIGH", output_strength="HIGH"),
                    bedrock.CfnGuardrail.ContentFilterConfigProperty(type="VIOLENCE", input_strength="MEDIUM", output_strength="MEDIUM"),
                    bedrock.CfnGuardrail.ContentFilterConfigProperty(type="HATE", input_strength="HIGH", output_strength="HIGH"),
                    bedrock.CfnGuardrail.ContentFilterConfigProperty(type="INSULTS", input_strength="MEDIUM", output_strength="MEDIUM"),
                    bedrock.CfnGuardrail.ContentFilterConfigProperty(type="MISCONDUCT", input_strength="MEDIUM", output_strength="MEDIUM"),
                    bedrock.CfnGuardrail.ContentFilterConfigProperty(type="PROMPT_ATTACK", input_strength="HIGH", output_strength="NONE"),
                ]
            ),
            sensitive_information_policy_config=bedrock.CfnGuardrail.SensitiveInformationPolicyConfigProperty(
                pii_entities_config=[
                    bedrock.CfnGuardrail.GuardrailPiiEntityConfigProperty(type="EMAIL", action="ANONYMIZE"),
                    bedrock.CfnGuardrail.GuardrailPiiEntityConfigProperty(type="PHONE", action="ANONYMIZE"),
                    bedrock.CfnGuardrail.GuardrailPiiEntityConfigProperty(type="SSN", action="BLOCK"),
                    bedrock.CfnGuardrail.GuardrailPiiEntityConfigProperty(type="CREDIT_DEBIT_CARD_NUMBER", action="BLOCK"),
                ],
            ),
            topic_policy_config=bedrock.CfnGuardrail.TopicPolicyConfigProperty(
                topics_config=[
                    bedrock.CfnGuardrail.GuardrailTopicConfigProperty(
                        name="Competitor Discussion", type="DENY",
                        definition="Comparing this product to competitor products",
                        examples=["How does this compare to ChatGPT?"],
                    ),
                    bedrock.CfnGuardrail.GuardrailTopicConfigProperty(
                        name="Internal Financials", type="DENY",
                        definition="Requests about internal company financial data",
                        examples=["What is the company revenue?"],
                    ),
                ]
            ),
            blocked_input_messaging="I can't respond to that request. Please try something else.",
            blocked_output_messaging="I can't provide that information. Please contact support.",
        )

        CfnOutput(self, "KnowledgeBaseId", value=self.knowledge_base.attr_knowledge_base_id)
        CfnOutput(self, "GuardrailId", value=self.guardrail.attr_guardrail_id)

    # =========================================================================
    # LAYER 8: STRANDS AGENT RUNTIME
    # =========================================================================
    def _create_strands_agent_runtime(self, stage_name: str) -> None:
        self.strands_agent_role = iam.Role(
            self, "StrandsAgentRole",
            assumed_by=iam.CompositePrincipal(
                iam.ServicePrincipal("lambda.amazonaws.com"),
                iam.ServicePrincipal("ecs-tasks.amazonaws.com"),
            ),
            role_name=f"{self.project_name}-strands-agent-{stage_name}",
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name("service-role/AWSLambdaBasicExecutionRole"),
                iam.ManagedPolicy.from_aws_managed_policy_name("service-role/AWSLambdaVPCAccessExecutionRole"),
            ],
        )

        # Bedrock model invocation
        self.strands_agent_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockModelInvoke",
            actions=["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],
            resources=[
                f"arn:aws:bedrock:{self.region}::foundation-model/anthropic.*",
                f"arn:aws:bedrock:{self.region}::foundation-model/amazon.*",
            ],
        ))

        # KB Retrieve
        self.strands_agent_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockKBRetrieve",
            actions=["bedrock:Retrieve", "bedrock:RetrieveAndGenerate"],
            resources=[self.knowledge_base.attr_knowledge_base_arn],
        ))

        # Guardrails
        self.strands_agent_role.add_to_policy(iam.PolicyStatement(
            sid="BedrockGuardrails",
            actions=["bedrock:ApplyGuardrail"],
            resources=[f"arn:aws:bedrock:{self.region}:{self.account}:guardrail/*"],
        ))

        # Lambda Agent Host
        self.strands_agent_lambda = _lambda.Function(
            self, "StrandsAgentFn",
            function_name=f"{self.project_name}-strands-agent-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.ARM_64,
            handler="index.handler",
            code=_lambda.Code.from_asset("src/strands_agent"),
            environment={
                "STAGE": stage_name,
                "DEFAULT_MODEL_ID": "anthropic.claude-sonnet-4-20250514-v1:0",
                "FAST_MODEL_ID": "anthropic.claude-3-haiku-20240307-v1:0",
                "SESSION_TABLE": self.agent_session_table.table_name,
                "AGENT_ARTIFACTS_BUCKET": self.agent_artifacts_bucket.bucket_name,
                "KNOWLEDGE_BASE_ID": self.knowledge_base.attr_knowledge_base_id,
                "GUARDRAIL_ID": self.guardrail.attr_guardrail_id,
                "MAX_TURNS": "30",
            },
            timeout=Duration.minutes(15),
            memory_size=512 if stage_name == "dev" else 1024,
            tracing=_lambda.Tracing.ACTIVE,
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS),
            security_groups=[self.lambda_sg],
            role=self.strands_agent_role,
        )

        self.agent_session_table.grant_read_write_data(self.strands_agent_role)
        self.agent_artifacts_bucket.grant_read_write(self.strands_agent_role)
        self.documents_bucket.grant_read(self.strands_agent_role)

        # ECS Fargate for long-running research
        self.ecs_cluster = ecs.Cluster(
            self, "WorkerCluster",
            cluster_name=f"{self.project_name}-workers-{stage_name}",
            vpc=self.vpc,
            container_insights=True,
        )

        self.strands_agent_task_def = ecs.FargateTaskDefinition(
            self, "StrandsAgentTaskDef",
            family=f"{self.project_name}-strands-agent-ecs-{stage_name}",
            cpu=1024, memory_limit_mib=2048,
            task_role=self.strands_agent_role,
        )

        self.strands_agent_task_def.add_container(
            "AgentContainer",
            container_name="strands-agent",
            image=ecs.ContainerImage.from_registry("public.ecr.aws/lambda/python:3.12"),
            environment={
                "STAGE": stage_name,
                "DEFAULT_MODEL_ID": "anthropic.claude-sonnet-4-20250514-v1:0",
                "SESSION_TABLE": self.agent_session_table.table_name,
                "AGENT_ARTIFACTS_BUCKET": self.agent_artifacts_bucket.bucket_name,
                "KNOWLEDGE_BASE_ID": self.knowledge_base.attr_knowledge_base_id,
            },
            logging=ecs.LogDrivers.aws_logs(stream_prefix="strands-agent",
                log_retention=logs.RetentionDays.ONE_MONTH),
        )

        CfnOutput(self, "StrandsAgentLambdaArn", value=self.strands_agent_lambda.function_arn)

    # =========================================================================
    # LAYER 4: API (REST + Cognito)
    # =========================================================================
    def _create_api_layer(self, stage_name: str) -> None:
        # Cognito User Pool
        self.user_pool = cognito.UserPool(
            self, "UserPool",
            user_pool_name=f"{self.project_name}-users-{stage_name}",
            sign_in_aliases=cognito.SignInAliases(email=True),
            self_sign_up_enabled=True,
            auto_verify=cognito.AutoVerifiedAttrs(email=True),
            mfa=cognito.Mfa.REQUIRED if stage_name == "prod" else cognito.Mfa.OPTIONAL,
            mfa_second_factor=cognito.MfaSecondFactor(sms=False, otp=True),
            password_policy=cognito.PasswordPolicy(
                min_length=12, require_lowercase=True, require_uppercase=True,
                require_digits=True, require_symbols=True,
            ),
            removal_policy=RemovalPolicy.RETAIN if stage_name == "prod" else RemovalPolicy.DESTROY,
        )

        self.user_pool_client = self.user_pool.add_client(
            "WebClient",
            user_pool_client_name=f"{self.project_name}-web-{stage_name}",
            auth_flows=cognito.AuthFlow(user_srp=True),
            o_auth=cognito.OAuthSettings(
                flows=cognito.OAuthFlows(authorization_code_grant=True),
                scopes=[cognito.OAuthScope.OPENID, cognito.OAuthScope.EMAIL, cognito.OAuthScope.PROFILE],
                callback_urls=["http://localhost:3000/callback"] if stage_name == "dev" else [f"https://{self.project_name}.example.com/callback"],
            ),
        )

        self.user_pool.add_domain("CognitoDomain",
            cognito_domain=cognito.CognitoDomainOptions(domain_prefix=f"{self.project_name}-{stage_name}"))

        # REST API
        self.rest_api = apigw.RestApi(
            self, "RestApi",
            rest_api_name=f"{self.project_name}-api-{stage_name}",
            deploy_options=apigw.StageOptions(
                stage_name=stage_name,
                logging_level=apigw.MethodLoggingLevel.INFO,
                data_trace_enabled=stage_name != "prod",
                tracing_enabled=True,
                throttling_rate_limit=100,
                throttling_burst_limit=200,
            ),
            default_cors_preflight_options=apigw.CorsOptions(
                allow_origins=apigw.Cors.ALL_ORIGINS,
                allow_methods=apigw.Cors.ALL_METHODS,
            ),
        )

        self.cognito_authorizer = apigw.CognitoUserPoolsAuthorizer(
            self, "CognitoAuth",
            cognito_user_pools=[self.user_pool],
        )

        # Document upload endpoint
        doc_resource = self.rest_api.root.add_resource("documents").add_resource("upload")
        doc_upload_fn = _lambda.Function(
            self, "DocIngestionFn",
            function_name=f"{self.project_name}-doc-ingestion-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.ARM_64,
            handler="index.handler",
            code=_lambda.Code.from_asset("src/document_ingestion"),
            environment={
                "STAGE": stage_name,
                "DOCUMENTS_BUCKET": self.documents_bucket.bucket_name,
                "KNOWLEDGE_BASE_ID": self.knowledge_base.attr_knowledge_base_id,
            },
            timeout=Duration.minutes(5),
            memory_size=512,
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS),
            security_groups=[self.lambda_sg],
        )
        self.documents_bucket.grant_read_write(doc_upload_fn)
        doc_resource.add_method("POST", apigw.LambdaIntegration(doc_upload_fn),
            authorization_type=apigw.AuthorizationType.COGNITO, authorizer=self.cognito_authorizer)

        CfnOutput(self, "ApiUrl", value=self.rest_api.url)
        CfnOutput(self, "UserPoolId", value=self.user_pool.user_pool_id)
        CfnOutput(self, "UserPoolClientId", value=self.user_pool_client.user_pool_client_id)

    # =========================================================================
    # LAYER 10: STRANDS AGENT FRONTEND (WebSocket + Session REST)
    # =========================================================================
    def _create_strands_agent_frontend(self, stage_name: str) -> None:
        # WebSocket API (API Gateway v2)
        self.agent_ws_api = apigwv2.CfnApi(
            self, "AgentWebSocketApi",
            name=f"{self.project_name}-agent-ws-{stage_name}",
            protocol_type="WEBSOCKET",
            route_selection_expression="$request.body.action",
        )

        ws_log_group = logs.LogGroup(
            self, "AgentWSAccessLogs",
            log_group_name=f"/{self.project_name}/{stage_name}/agent-ws-access-logs",
            retention=logs.RetentionDays.ONE_MONTH if stage_name != "prod" else logs.RetentionDays.ONE_YEAR,
            removal_policy=RemovalPolicy.DESTROY,
        )

        self.agent_ws_stage = apigwv2.CfnStage(
            self, "AgentWSStage",
            api_id=self.agent_ws_api.ref,
            stage_name=stage_name,
            auto_deploy=True,
            default_route_settings=apigwv2.CfnStage.RouteSettingsProperty(
                logging_level="INFO",
                data_trace_enabled=stage_name != "prod",
                throttling_rate_limit=100,
                throttling_burst_limit=200,
            ),
            access_log_settings=apigwv2.CfnStage.AccessLogSettingsProperty(
                destination_arn=ws_log_group.log_group_arn,
            ),
        )

        # WebSocket Lambda Role
        ws_lambda_role = iam.Role(
            self, "AgentWSLambdaRole",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name("service-role/AWSLambdaBasicExecutionRole"),
                iam.ManagedPolicy.from_aws_managed_policy_name("service-role/AWSLambdaVPCAccessExecutionRole"),
            ],
        )
        ws_lambda_role.add_to_policy(iam.PolicyStatement(
            actions=["execute-api:ManageConnections"],
            resources=[f"arn:aws:execute-api:{self.region}:{self.account}:{self.agent_ws_api.ref}/{stage_name}/POST/@connections/*"],
        ))
        self.strands_agent_lambda.grant_invoke(ws_lambda_role)

        ws_env = {
            "STAGE": stage_name,
            "CONNECTION_TABLE": f"{self.project_name}-agent-ws-connections-{stage_name}",
            "SESSION_TABLE": self.agent_session_table.table_name,
            "AGENT_FUNCTION_NAME": self.strands_agent_lambda.function_name,
            "WS_ENDPOINT": f"https://{self.agent_ws_api.ref}.execute-api.{self.region}.amazonaws.com/{stage_name}",
        }

        # WebSocket handlers
        self.ws_connect_fn = _lambda.Function(self, "AgentWSConnectFn",
            function_name=f"{self.project_name}-ws-connect-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12, architecture=_lambda.Architecture.ARM_64,
            handler="index.handler", code=_lambda.Code.from_asset("src/agent_frontend/ws_connect"),
            environment=ws_env, timeout=Duration.seconds(10), memory_size=256, role=ws_lambda_role)

        self.ws_message_fn = _lambda.Function(self, "AgentWSMessageFn",
            function_name=f"{self.project_name}-ws-message-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12, architecture=_lambda.Architecture.ARM_64,
            handler="index.handler", code=_lambda.Code.from_asset("src/agent_frontend/ws_message"),
            environment=ws_env, timeout=Duration.minutes(15), memory_size=512, role=ws_lambda_role)

        self.ws_disconnect_fn = _lambda.Function(self, "AgentWSDisconnectFn",
            function_name=f"{self.project_name}-ws-disconnect-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12, architecture=_lambda.Architecture.ARM_64,
            handler="index.handler", code=_lambda.Code.from_asset("src/agent_frontend/ws_disconnect"),
            environment=ws_env, timeout=Duration.seconds(10), memory_size=256, role=ws_lambda_role)

        # Wire integrations
        for route_key, fn, fn_id in [
            ("$connect", self.ws_connect_fn, "Connect"),
            ("$default", self.ws_message_fn, "Message"),
            ("$disconnect", self.ws_disconnect_fn, "Disconnect"),
        ]:
            integration = apigwv2.CfnIntegration(self, f"AgentWSInt{fn_id}",
                api_id=self.agent_ws_api.ref, integration_type="AWS_PROXY",
                integration_uri=f"arn:aws:apigateway:{self.region}:lambda:path/2015-03-31/functions/{fn.function_arn}/invocations")
            apigwv2.CfnRoute(self, f"AgentWSRoute{fn_id}",
                api_id=self.agent_ws_api.ref, route_key=route_key, target=f"integrations/{integration.ref}")
            fn.add_permission(f"APIGW-{fn_id}", principal=iam.ServicePrincipal("apigateway.amazonaws.com"),
                source_arn=f"arn:aws:execute-api:{self.region}:{self.account}:{self.agent_ws_api.ref}/*")

        # Connection table
        self.ws_connection_table = ddb.Table(self, "AgentWSConnectionTable",
            table_name=f"{self.project_name}-agent-ws-connections-{stage_name}",
            partition_key=ddb.Attribute(name="connection_id", type=ddb.AttributeType.STRING),
            billing_mode=ddb.BillingMode.PAY_PER_REQUEST, time_to_live_attribute="ttl",
            removal_policy=RemovalPolicy.DESTROY)
        self.ws_connection_table.grant_read_write_data(ws_lambda_role)
        self.agent_session_table.grant_read_write_data(ws_lambda_role)

        # Session management REST endpoints
        agent_resource = self.rest_api.root.add_resource("agent")
        invoke_resource = agent_resource.add_resource("invoke")
        invoke_resource.add_method("POST", apigw.LambdaIntegration(self.strands_agent_lambda, proxy=True),
            authorization_type=apigw.AuthorizationType.COGNITO, authorizer=self.cognito_authorizer)

        self.session_mgmt_fn = _lambda.Function(self, "AgentSessionMgmtFn",
            function_name=f"{self.project_name}-sessions-api-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12, architecture=_lambda.Architecture.ARM_64,
            handler="index.handler", code=_lambda.Code.from_asset("src/agent_frontend/session_mgmt"),
            environment={"STAGE": stage_name, "SESSION_TABLE": self.agent_session_table.table_name},
            timeout=Duration.seconds(10), memory_size=256)
        self.agent_session_table.grant_read_write_data(self.session_mgmt_fn)

        sessions_resource = agent_resource.add_resource("sessions")
        sessions_resource.add_method("GET", apigw.LambdaIntegration(self.session_mgmt_fn, proxy=True),
            authorization_type=apigw.AuthorizationType.COGNITO, authorizer=self.cognito_authorizer)
        session_detail = sessions_resource.add_resource("{session_id}")
        session_detail.add_method("GET", apigw.LambdaIntegration(self.session_mgmt_fn, proxy=True),
            authorization_type=apigw.AuthorizationType.COGNITO, authorizer=self.cognito_authorizer)
        session_detail.add_method("DELETE", apigw.LambdaIntegration(self.session_mgmt_fn, proxy=True),
            authorization_type=apigw.AuthorizationType.COGNITO, authorizer=self.cognito_authorizer)

        # Frontend config SSM
        ssm.StringParameter(self, "AgentFrontendConfig",
            parameter_name=f"/{self.project_name}/{stage_name}/agent-frontend-config",
            string_value=json.dumps({
                "cognito": {"user_pool_id": self.user_pool.user_pool_id,
                    "app_client_id": self.user_pool_client.user_pool_client_id, "region": self.region},
                "api": {"rest_endpoint": self.rest_api.url,
                    "ws_endpoint": f"wss://{self.agent_ws_api.ref}.execute-api.{self.region}.amazonaws.com/{stage_name}"},
                "features": {"streaming_enabled": True, "session_history_enabled": True, "file_upload_enabled": True},
            }))

        CfnOutput(self, "AgentWebSocketURL",
            value=f"wss://{self.agent_ws_api.ref}.execute-api.{self.region}.amazonaws.com/{stage_name}")

    # =========================================================================
    # LAYER 9: STRANDS AGENTCORE (Gateway + Memory + OAuth2)
    # =========================================================================
    def _create_strands_agentcore(self, stage_name: str) -> None:
        self.agentcore_user_pool = cognito.UserPool(
            self, "AgentCoreUserPool",
            user_pool_name=f"{self.project_name}-agentcore-{stage_name}",
            removal_policy=RemovalPolicy.DESTROY if stage_name != "prod" else RemovalPolicy.RETAIN,
            sign_in_aliases=cognito.SignInAliases(email=True),
            self_sign_up_enabled=False,
        )

        resource_server = self.agentcore_user_pool.add_resource_server("AgentCoreRS",
            identifier=f"{self.project_name}-gateway",
            scopes=[cognito.ResourceServerScope(scope_name="tools.invoke", scope_description="Invoke tools via Gateway")])

        self.agentcore_app_client = self.agentcore_user_pool.add_client("AgentCoreClient",
            user_pool_client_name=f"{self.project_name}-agent-client-{stage_name}",
            generate_secret=True,
            o_auth=cognito.OAuthSettings(
                flows=cognito.OAuthFlows(client_credentials=True),
                scopes=[cognito.OAuthScope.resource_server(resource_server,
                    cognito.ResourceServerScope(scope_name="tools.invoke", scope_description="Invoke tools"))],
            ))

        self.agentcore_user_pool.add_domain("AgentCoreDomain",
            cognito_domain=cognito.CognitoDomainOptions(domain_prefix=f"{self.project_name}-ac-{stage_name}"))

        self.agentcore_client_secret = sm.Secret(self, "AgentCoreClientSecret",
            secret_name=f"{self.project_name}/{stage_name}/agentcore-gateway-credentials",
            encryption_key=self.kms_key)
        self.agentcore_client_secret.grant_read(self.strands_agent_role)

        # Gateway tool Lambdas
        db_tool_fn = _lambda.Function(self, "GatewayToolDB",
            function_name=f"{self.project_name}-gateway-tool-db-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12, architecture=_lambda.Architecture.ARM_64,
            handler="index.handler", code=_lambda.Code.from_asset("src/gateway_tools/db_tool"),
            environment={"STAGE": stage_name, "SESSION_TABLE": self.agent_session_table.table_name},
            timeout=Duration.seconds(30), memory_size=256,
            vpc=self.vpc, vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS),
            security_groups=[self.lambda_sg])
        self.agent_session_table.grant_read_data(db_tool_fn)

        api_tool_fn = _lambda.Function(self, "GatewayToolAPI",
            function_name=f"{self.project_name}-gateway-tool-api-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12, architecture=_lambda.Architecture.ARM_64,
            handler="index.handler", code=_lambda.Code.from_asset("src/gateway_tools/api_tool"),
            environment={"STAGE": stage_name}, timeout=Duration.seconds(30), memory_size=256)

        for fn in [db_tool_fn, api_tool_fn]:
            fn.add_permission("AgentCoreInvoke", principal=iam.ServicePrincipal("bedrock.amazonaws.com"),
                action="lambda:InvokeFunction")

        # Memory config
        ssm.StringParameter(self, "AgentCoreMemoryConfig",
            parameter_name=f"/{self.project_name}/{stage_name}/agentcore/memory-config",
            string_value=json.dumps({
                "memory_id": f"{self.project_name}-memory-{stage_name}",
                "strategies": [
                    {"type": "SUMMARY"}, {"type": "USER_PREFERENCE"}, {"type": "SEMANTIC"},
                ],
            }))

        CfnOutput(self, "AgentCoreUserPoolId", value=self.agentcore_user_pool.user_pool_id)

    # =========================================================================
    # LAYER 11: STRANDS AGENT EVAL
    # =========================================================================
    def _create_strands_agent_eval(self, stage_name: str) -> None:
        self.eval_runner_fn = _lambda.Function(
            self, "AgentEvalRunnerFn",
            function_name=f"{self.project_name}-eval-runner-{stage_name}",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.ARM_64,
            handler="index.handler",
            code=_lambda.Code.from_asset("src/agent_eval/runner"),
            environment={
                "STAGE": stage_name,
                "EVAL_RESULTS_TABLE": self.eval_results_table.table_name,
                "AGENT_FUNCTION_NAME": self.strands_agent_lambda.function_name,
                "JUDGE_MODEL_ID": "anthropic.claude-sonnet-4-20250514-v1:0",
                "DATASET_BUCKET": self.eval_dataset_bucket.bucket_name,
                "EVAL_NAMESPACE": f"{self.project_name}/AgentEval",
                "PROJECT_NAME": self.project_name,
            },
            timeout=Duration.minutes(5),
            memory_size=512,
            role=self.strands_agent_role,
        )
        self.eval_results_table.grant_read_write_data(self.eval_runner_fn)
        self.strands_agent_lambda.grant_invoke(self.eval_runner_fn)
        self.eval_dataset_bucket.grant_read(self.eval_runner_fn)

        # Step Functions eval workflow
        load_dataset = sfn_tasks.LambdaInvoke(self, "LoadDataset",
            lambda_function=self.eval_runner_fn,
            payload=sfn.TaskInput.from_object({
                "action": "load_dataset", "dataset_key.$": "$.dataset_key", "eval_run_id.$": "$.eval_run_id"}),
            result_path="$.dataset", output_path="$")

        run_test_case = sfn_tasks.LambdaInvoke(self, "RunTestCase",
            lambda_function=self.eval_runner_fn,
            payload=sfn.TaskInput.from_object({
                "action": "run_test_case", "eval_run_id.$": "$.eval_run_id", "test_case.$": "$$.Map.Item.Value"}),
            result_path="$.result")

        eval_map = sfn.Map(self, "EvalMapState",
            items_path="$.dataset.Payload.test_cases", max_concurrency=5, result_path="$.results")
        eval_map.iterator(run_test_case)

        aggregate = sfn_tasks.LambdaInvoke(self, "AggregateResults",
            lambda_function=self.eval_runner_fn,
            payload=sfn.TaskInput.from_object({
                "action": "aggregate", "eval_run_id.$": "$.eval_run_id", "results.$": "$.results"}),
            result_path="$.summary")

        quality_gate = sfn.Choice(self, "QualityGate")
        gate_pass = sfn.Pass(self, "EvalPassed", result=sfn.Result.from_object({"status": "PASSED"}))
        gate_fail = sfn.Fail(self, "EvalFailed", cause="Eval score below threshold", error="EVAL_QUALITY_GATE_FAILED")
        quality_gate.when(
            sfn.Condition.number_greater_than_equals("$.summary.Payload.overall_score", 0.85), gate_pass
        ).otherwise(gate_fail)

        definition = load_dataset.next(eval_map).next(aggregate).next(quality_gate)

        self.eval_state_machine = sfn.StateMachine(self, "AgentEvalSFN",
            state_machine_name=f"{self.project_name}-agent-eval-{stage_name}",
            definition_body=sfn.DefinitionBody.from_chainable(definition),
            timeout=Duration.hours(1), tracing_enabled=True)

        # CloudWatch alarms
        EVAL_NS = f"{self.project_name}/AgentEval"
        eval_alarm = cw.Alarm(self, "AgentEvalScoreAlarm",
            alarm_name=f"{self.project_name}-eval-score-{stage_name}",
            metric=cw.Metric(namespace=EVAL_NS, metric_name="OverallScore",
                dimensions_map={"Stage": stage_name}, period=Duration.hours(1), statistic="Average"),
            threshold=0.85, comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            evaluation_periods=1, treat_missing_data=cw.TreatMissingData.NOT_BREACHING)
        eval_alarm.add_alarm_action(cw_actions.SnsAction(self.alert_topic))

        # CICD config
        ssm.StringParameter(self, "AgentEvalCICDConfig",
            parameter_name=f"/{self.project_name}/{stage_name}/agent-eval/cicd-config",
            string_value=json.dumps({
                "state_machine_arn": self.eval_state_machine.state_machine_arn,
                "dataset_bucket": self.eval_dataset_bucket.bucket_name,
                "min_score_threshold": 0.85,
            }))

        CfnOutput(self, "AgentEvalSFNArn", value=self.eval_state_machine.state_machine_arn)

    # =========================================================================
    # LAYER 5: FRONTEND (S3 + CloudFront + WAF)
    # =========================================================================
    def _create_frontend(self, stage_name: str) -> None:
        self.frontend_bucket = s3.Bucket(
            self, "FrontendBucket",
            bucket_name=f"{self.project_name}-frontend-{stage_name}-{self.account}",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        oai = cloudfront.OriginAccessIdentity(self, "OAI")
        self.frontend_bucket.grant_read(oai)

        # WAF
        waf_acl = wafv2.CfnWebACL(
            self, "FrontendWAF",
            name=f"{self.project_name}-waf-{stage_name}",
            scope="CLOUDFRONT",
            default_action=wafv2.CfnWebACL.DefaultActionProperty(allow={}),
            visibility_config=wafv2.CfnWebACL.VisibilityConfigProperty(
                cloud_watch_metrics_enabled=True,
                metric_name=f"{self.project_name}-waf-{stage_name}",
                sampled_requests_enabled=True,
            ),
            rules=[
                wafv2.CfnWebACL.RuleProperty(
                    name="AWSManagedRulesCommonRuleSet",
                    priority=1,
                    override_action=wafv2.CfnWebACL.OverrideActionProperty(
                        count={} if stage_name == "dev" else None,
                        none={} if stage_name != "dev" else None,
                    ),
                    statement=wafv2.CfnWebACL.StatementProperty(
                        managed_rule_group_statement=wafv2.CfnWebACL.ManagedRuleGroupStatementProperty(
                            vendor_name="AWS", name="AWSManagedRulesCommonRuleSet",
                        ),
                    ),
                    visibility_config=wafv2.CfnWebACL.VisibilityConfigProperty(
                        cloud_watch_metrics_enabled=True,
                        metric_name="CommonRuleSet",
                        sampled_requests_enabled=True,
                    ),
                ),
                wafv2.CfnWebACL.RuleProperty(
                    name="RateLimit",
                    priority=2,
                    action=wafv2.CfnWebACL.RuleActionProperty(
                        count={} if stage_name == "dev" else None,
                        block={} if stage_name != "dev" else None,
                    ),
                    statement=wafv2.CfnWebACL.StatementProperty(
                        rate_based_statement=wafv2.CfnWebACL.RateBasedStatementProperty(
                            limit=1000, aggregate_key_type="IP",
                        ),
                    ),
                    visibility_config=wafv2.CfnWebACL.VisibilityConfigProperty(
                        cloud_watch_metrics_enabled=True,
                        metric_name="RateLimit",
                        sampled_requests_enabled=True,
                    ),
                ),
            ],
        )

        price_class = cloudfront.PriceClass.PRICE_CLASS_ALL if stage_name == "prod" else cloudfront.PriceClass.PRICE_CLASS_100

        self.distribution = cloudfront.Distribution(
            self, "FrontendDistribution",
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.S3Origin(self.frontend_bucket, origin_access_identity=oai),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                cache_policy=cloudfront.CachePolicy.CACHING_OPTIMIZED,
            ),
            default_root_object="index.html",
            error_responses=[
                cloudfront.ErrorResponse(http_status=404, response_page_path="/index.html", response_http_status=200),
                cloudfront.ErrorResponse(http_status=403, response_page_path="/index.html", response_http_status=200),
            ],
            price_class=price_class,
            web_acl_id=waf_acl.attr_arn,
        )

        CfnOutput(self, "CloudFrontURL", value=f"https://{self.distribution.distribution_domain_name}")
        CfnOutput(self, "FrontendBucketName", value=self.frontend_bucket.bucket_name)
